# Generated by Django 3.0.7 on 2020-06-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('instagram_link', models.URLField()),
                ('site_profile_link', models.URLField(null=True)),
                ('sport', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-instagram__followers'],
            },
        ),
    ]
