# Generated by Django 3.0.7 on 2020-06-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.IntegerField(null=True)),
                ('followings', models.IntegerField(null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('profile_picture', models.URLField()),
                ('profile_verifyed', models.BooleanField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram', to='overall.Team')),
            ],
            options={
                'ordering': ['-followers'],
            },
        ),
    ]
