# Generated by Django 3.0.7 on 2020-06-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overall', '0002_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
