# Generated by Django 3.0.7 on 2020-06-20 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nflTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('instagram_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='nflInstagrams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.IntegerField(null=True)),
                ('followings', models.IntegerField(null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('profile_picture', models.URLField()),
                ('profile_verifyed', models.BooleanField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.nflTeams')),
            ],
            options={
                'ordering': ['-followers'],
            },
        ),
    ]
