# Generated by Django 3.0.7 on 2020-06-23 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0004_auto_20200623_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nflinstagrams',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram', to='nfl.nflTeams'),
        ),
    ]
