# Generated by Django 3.0.7 on 2020-06-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0005_auto_20200623_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nflteams',
            options={'ordering': ['-instagram__followers']},
        ),
    ]
